### PR TITLE
OBS compliant packaging

### PR DESCRIPTION
**Pull request by timkol**
Packaging files are based on fks-texmf ones.

Should be /etc/bash_completion.d  mentioned in conffiles (currently is)?

We should move everything from /usr/local/share to /usr/share (need of editing some scripts).

### CODE REVIEW

**Review by Auratons — COMMENTED** [review]
Za mě je to stejné, jako u fks-templates. Proč to chceme do /usr/share?

**Review by cevro — APPROVED** [review]

**Review by Werkov — APPROVED** [review]
We want it out of `/usr/local` because it's a path reserved for unpackaged SW. It's a historical error.

There are dependencies in fks-templates (maybe more) so this migration should be another PR.

Bash completion shouldn't be considered a config file. I don't see it currently is marked as a config file so it should be OK.

**Comment by timkol** [comment]
@Werkov According to https://www.debian.org/doc/manuals/maint-guide/dother.en.html#conffiles, every file in /etc is by default added to conffiles. Also I've found, there exists dh_bash-completion, but I don't have any experience with it and don't know which bash-completion utility it is about.

**Comment by timkol** [comment]
@Werkov And indeed in /var/lib/dpkg/info/fks-scripts.conffiles is bash_completion.d/fks listed. But for instance apache2 and debconf packages have their bash_completion in conffiles too, so I don't consider it as a bug (or at least not as severe bug). Closing and merging.

**Pull request merged**
